- name: installed keepalived server
  yum:
    name: keepalived
    state: present

- name: configure keepalived server
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify: restart keepalived

- name: systemd keepalived server
  systemd:
    name: keepalived
    state: started
    enabled: yes
