- name: configure nfs server
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  notify: restart nfs server

- name: create nfs share directory
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ web_process_user }}"
    group: "{{ web_process_group }}"
    recurse: yes
  loop:
    - "{{ nfs_wecenter }}"
    - "{{ nfs_zrlog }}"
    - "{{ nfs_kodcloud }}"
 
- name: systemd nfs server
  systemd:
    name: nfs
    state: started
    enabled: yes
