- name: installed mariadb server
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - mariadb-server
      - mariadb
      - MySQL-python

- name: configure mariadb server
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf

- name: systemd mariadb server
  systemd:
    name: mariadb
    state: started
    enabled: yes

- name: create database
  mysql_db:
    login_user: root
    login_password: oldxu.com
    name: "{{ item }}"
    state: present
  loop:
    - wordpress
    - zh
    - zrlog

- name: create remote usr name 'all' and password 'oldxu.com' with all database privileges
  mysql_user:
    login_user: root
    login_password: oldxu.com
    name: all
    host: '%'
    password: oldxu.com
    priv: '*.*:ALL'
    state: present
